### ISSUE TITLE
option for custom genome

### ISSUE THREAD

**Issue by arunprasanna83** [snakemake-workflows/rna-seq-kallisto-sleuth#131] opened 2024-11-07 07:58 UTC
Hi, 
Is it possible to use it for genomes other than human? The config.yaml file does not have an option for unpublished genomes.
Thanks.

**Comment by dlaehnemann** [comment] 2024-11-07 12:08
You can use any species that has a reference genome available via Ensembl, for a quick overview table see here:
https://www.ensembl.org/info/about/species.html

For the list including the full species name that you will need to provide in the `config.yaml`, you can consult the full list for the `release` that you are planning to use, for example this one for the current latest Ensembl `release-113`:
https://ftp.ensembl.org/pub/release-113/species_EnsemblVertebrates.txt

You can configure this right here in the config.yaml file:
https://github.com/snakemake-workflows/rna-seq-kallisto-sleuth/blob/8b57d60b713fe3994f95afc069d59cb089371524/config/config.yaml#L16-L21

Alternatively, if the genome you are looking for is not in there, you can manually provide a file with the correct path and file name as expected by downstream rules; or, even better (because more reproducible), you can modify or replace the whole download rule with one that downloads your genome from a known online source. For the latter, you can use a `use rule some_task from other_workflow as other_some_task with:` statement after module important, as described here:
https://snakemake.readthedocs.io/en/stable/snakefiles/modularization.html#modules

I hope one of those options helps you and will close the issue for now. Feel free to ask further questions or reopen if this doesn't answer your question at all.

**Closed by dlaehnemann** 2024-11-07 12:08 UTC
